spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: public-user-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/auth/login
        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/user/**
          filters:
            - name: JwtFilter

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

server:
  port: 9000